[package]
name = "mint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
motif = { version = "0.1.0", path = "../motif" }
error_reporter = { version = "0.1.0", path = "../../util/error_reporter" }